program: Assignment-1-q3-i.py
method: grid
metric:
  goal: maximize
  name: accuracy
parameters:
  #dropout:
   # values: [0.1, 0.2, 0.4, 0.5, 0.7]
  #channels_one:
   # values: [10, 12, 14, 16, 18, 20]
  #channels_two:
    #values: [24, 28, 32, 36, 40, 44]
  learning_rate:
    values: [0.001, 0.005, 0.0005, 0.03, 1.3, 1.2]
  epochs:
    values: [2, 5, 10, 15]
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 27